version: '3.7'

services:
  # client:
  #   container_name: client
  #   build: ./client
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - ./client:/srv/app/tokopilsatdb-client
  # admin:
  #   container_name: admin
  #   build: ./admin
  #   ports:
  #     - '3032:3032'
  #   volumes:
  #     - ./admin:/srv/app/tokopilsatdb-admin
  #     - /srv/app/tokopilsatdb-admin/node_modules
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./server:/srv/app/tokopilsatdb-server
    environment:
      NODE_ENV: "development"
      HOST: "0.0.0.0"
      PORT: 8080
    env_file:
      - ./db.env
      - ./jwt.env
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./db.env
