version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - "3001:3001"
    volumes:
      - ./client:/srv/app/tokopilsatdb-client
#    networks:
#      - proxy
  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile-prod
    ports:
      - "3032:3032"
    volumes:
      - ./admin:/srv/app/tokopilsatdb-admin
#    networks:
#      - proxy
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile-prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./server:/srv/app/tokopilsatdb-server
    environment:
      NODE_ENV: "production"
      HOST: "tokopilsatdb.com"
      PORT: 8080
    env_file:
      - ./db.env
    networks:
#      - proxy
      - db
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    env_file:
      - ./db.env
    networks:
      - db
#  fire up nginx via baremetal nginx instead of docker
#  nginx:
#   container_name: nginx
#   build: ./nginx
#   volumes:
#     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#   ports:
#      - '80:80'
#   networks:
#     - proxy
#   depends_on:
#     - server
#     - client

networks:
#  proxy:
  db:
