export const GET_COLLECTION_LIST = 'collection/GET_COLLECTION_LIST';

export const SET_FORM_COLLECTION_MEDIA = 'collection/SET_FORM_COLLECTION_MEDIA';
export const SET_FORM_COLLECTION_LABEL = 'collection/SET_FORM_COLLECTION_LABEL';
export const UPLOAD_FORM_COLLECTION_SUCCESS = 'collection/UPLOAD_FORM_COLLECTION_SUCCESS';
