export const GET_PRODUCT_LIST = 'product/GET_PRODUCT_LIST';

export const SET_FORM_PRODUCT_MEDIA = 'product/SET_FORM_PRODUCT_MEDIA';
export const SET_FORM_PRODUCT_NAME = 'product/SET_FORM_PRODUCT_NAME';
export const SET_FORM_PRODUCT_PRICE = 'product/SET_FORM_PRODUCT_PRICE';
export const SET_FORM_PRODUCT_DESCRIPTION = 'product/SET_FORM_PRODUCT_DESCRIPTION';
export const SET_FORM_PRODUCT_COLLECTION = 'product/SET_FORM_PRODUCT_COLLECTION';

export const UPLOAD_FORM_PRODUCT_SUCCESS = 'product/UPLOAD_FORM_PRODUCT_SUCCESS';
